= Define Extrapolate

Extrapolate is a blog.

Not a travel blog, or a food blog, or a book/movie review blog, though these are all things that I enjoy and will likely find themselves cameos in posts here and there. Extrapolate isn't a daily/weekly/{insert regular time interval}-ly journal blog either, though it might seem like it at times. 

Extrapolate is an ongoing record of the more interesting "ideas" that find their ways into my mind. I hesitate to use the word "ideas" here because (at least in my personal connotation-dictionary) __ideas__ are discrete, and useful in some compacity. The things I think about are hardly discrete and rarely useful, instead occupying the hazy intellectual territory at the intersection of personal experience and pattern recognition. 

That last bit probably makes zero sense to you, so let me try to explain. As I go about my exceptionally average life, I (like my 7+ billion fellow humans) inevitably accumulate a set of experiences, memories, ideas. __These__ are discrete; I can mentally point to a conversation I've had, or an article I've read, or a place I've been to. In isolation, these "points" are hardly worth thinking about, much less writing about. If I led a more interesting life, I could've made this blog a place to simply `Ctrl+C` `Ctrl+V` these experiences/ideas from my sensory receptors, with a dash of introspection. The analytical analog of an Instagram filter, if you will.

But for better or worse, my life __is__ pretty mundane, so instead I 