= Railroads, Silicon, and Tigers: My Asian American Dream

__Disclaimer: This essay is based entirely on personal experience and observations. I realize that I come from a place of privelege, and that this essay hardly applies to all Asian Americans. But I'm not here to write universal truths. I'm here to write about me.__

My story is neither universal nor unique, neither inspirational nor tragic. And it sure as hell isn't simple. 

First, a little about myself. I am 18. I am male. I am a first generation Chinese American. I was born and raised in Silicon Valley suburbia. Affluent and predominantly white, but with a sizable Asian population. I had a happy, if stereotypically Asian, childhood, which included piano lessons and math competitions. My enough-to-scrape-an-A philosophy in high school somehow got me into the school down the street, and now I study computer science at Stanford. 

This would be a lot of personal information to divulge for a suppposedly-anonymous blog, if it weren't for the fact that the entire last paragraph is generic as fuck. Even knowing my age, gender, ethnicity, school, and major, you'd still be left with about a 1 in a 100 crapshoot at guessing who I am. My point being, I'm not all that special. I'm a walking stereotype, despite the fact that I spent much of my childhood running from stereotypes.

At this point, the more skeptical (read: racially-obtuse) reader might argue that I have nothing to complain about, that these are "positive" stereotypes or something along those lines. And it's true, I have never been stopped and frisked, or searched without a warrant, or "randomly" chosen by the TSA. I __could__ talk about how Asian males have been emasculated by popular media, or how the "bamboo ceiling" is screwing us over in the corporate world. But my romantic and professional careers are a tad too non-existent for me to comment with authority. But what I __have__ felt, and what I'll be writing about, is a loss of identity. 

Every part of my "identity" that conforms with some stereotype might as well not exist, and the resulting whole is palpably smaller, less significant. The difference is small; it hovers around that JND threshold so that most of the time it doesn't matter. But when it does, it fucking __sucks__. To feel like slightly less of an individual than your peers? Yeah, fuck that. 

At __this__ point, the skeptical reader might argue that it's __my__ fault for conforming to stereotypes. That I __could__ just major in Comparative Literature; hell, I could drop out of school altogether. And sometimes I do wonder where I'd be if I had been a bit more rebellious growing up. I quit piano pretty early on, but what if I had told my parents that I hated math, what if I had stuck to art? What if I had gone to some tiny liberal arts college on the East coast and majored in the humanities? Things would undoubtedly be different, but there's a __reason__ that these are hypotheticals and not reality, there's a reason these stereotypes exist at all. 

__Full disclosure: I am hilariously underqualified to be presenting the following theory, but who gives a shit:__

The "model minority" stereotypes, the "tiger mom" parenting phenomena, the overdone jokes about Asian doctors and engineers, they exist for a reason. It's a cultural thing. It's the current chapter of a centuries-old narrative that spans generations and the Pacific. If I had to guess, this narrative probably starts with Confucius or some other long-dead Chinese guy who ingrained the values of education, meritocracy, and progress in the ethos of 