= Railroads, Silicon, and Tigers: My Asian American Dream

__Disclaimer: This essay is based entirely on personal experience and observations. I realize that I come from a place of privelege, and that this essay hardly applies to all Asian Americans. But I'm not here to write universal truths. I'm here to write about me.__

My story is neither universal nor unique, neither inspirational nor tragic. And it sure as hell isn't simple. 

First, a little about myself. I am 18. I am male. I am a first generation Chinese American. I was born and raised in Silicon Valley suburbia. Affluent and predominantly white, but with a sizable Asian population. I had a happy, if stereotypically Asian, childhood, which included piano lessons and math competitions. My enough-to-scrape-an-A philosophy in high school somehow got me into the school down the street, and now I study computer science at Stanford. 

This would be a lot of personal information to divulge for a suppposedly-anonymous blog, if it weren't for the fact that the entire last paragraph is generic as fuck. Even knowing my age, gender, ethnicity, school, and major, you'd still be left with about a 1 in a 100 crapshoot at guessing who I am. My point being, I'm not all that special. I'm a walking stereotype, despite the fact that I spent much of my childhood running from stereotypes.

At this point, the more skeptical (read: racially-obtuse) reader might argue that I have nothing to complain about, that these are "positive" stereotypes or something along those lines. And it's true, I have never been stopped and frisked, or searched without a warrant, or "randomly" chosen by the TSA. I __could__ talk about how Asian males have been emasculated by popular media, or how the "bamboo ceiling" is screwing us over in the corporate world. But my romantic and professional careers are a tad too non-existent for me to comment with authority. So instead, I'll be writing about identity, or lack thereof. 

Each part of my "identity" that conforms with some stereotype might as well not exist, and the resulting whole is palpably smaller, less significant. Whereas an interest in number theory or video games might add to my white counterpart's quirkiness, in my case they add nothing but reinforced preconceptions. The difference is small; it hovers around that JND threshold so that most of the time it doesn't matter. But when it does, it's pretty shitty. To feel like slightly less of an individual than your peers? Yeah, fuck that. 

At __this__ point, the skeptical reader might argue that it's __my__ fault for conforming to stereotypes. That I __could__ just major in Comparative Literature; hell, I could drop out of school altogether. And sometimes I do wonder where I'd be if I were a bit more rebellious. What if I had stuck to art instead of math? What if I had gone to some tiny liberal arts college on the East coast and majored in something humanities-related? Things would undoubtedly be different, but I honestly don't know how much agency I had in the whole matter. There's a __reason__ that these are hypotheticals and not reality, and there's a reason these stereotypes exist at all. 

__Full disclosure: I am hilariously underqualified to be presenting the following theory, but I don't really give a shit.__

The "model minority" stereotypes, the "tiger mom" parenting phenomena, the overdone jokes about Asian doctors and engineers, they exist for a reason. It's a cultural thing. It's the current chapter of a centuries-old narrative that spans generations and the Pacific. If I had to guess, this narrative probably starts with Confucius or some other long-dead philosopher who forever ingrained the values of education, family, and progress in the ethos of Chinese society. What matters now is how these values manifest, thousands of years and miles forward. 

I can only explain what I mean anecdotally, so here's some quick family history. From what I've heard, my great-grandfather was pretty damn successful, until he got fucked over by the Cultural Revolution. With one stroke of bad luck, he was back to square one. Most of his money was gone, but his value of education and hard work were passed down to his children and grandchildren. My parents, like many others of their generation, immigrated to the states in search of PhDs and a more stable socio-economic ladder to climb. Which brings us back to me: born into a upper-middle class family, studying at a prestigious university.

The trend I see is upwards. Not the Horatio Alger-type meteoric rise glorified in American media, especially here in the Silicon Valley. It's a slow and steady incline. Each successive generation ends up a few rungs above their parents, with the exception of that small communist hiccup I mentioned. I have been and continue to be pushed upwards by who-knows-how-many generations' worth of upwards socio-economic momentum. I'm just following the script, because I don't want to be the first selfish one in my lineage to do otherwise. In the Silicon Valley, the path forward is glaringly obvious: tech. So the reason that I am studying computer science is really a mixture (with unknown proportions) of personal interest, location, and what you'd either call "fate" or "unspoken familial responsibility". 

This is the version of the American Dream that I've inherited. The textbook, materialistic definition I was taught in school. As American as it gets, even if it was first dreamt up in China. Jeb Bush can go fuck himself with an anchor. 

This is also the version of the American Dream that seems to be going extinct. 