= What Matters, Revisited

Approximately one and a half years ago, I was asked (via college application, no less) an interesting question. "What matters most to you, and why? (250 words)" 

Having existed for barely seventeen years, I felt immensely unprepared to answer this question. After all, in the moment what seemed to matter most was that I finish those fucking college applications before their respective deadlines. I figured that my "real" answer would fall somewhere between family and friends, happiness and success. But when put into words, these values seemed contrived and oh so __obvious__. These concepts are so incredibly weighty, yet their semantic representations are so ordinary and overused. Words like "happiness" and "friendship" feel so hollow to say, even more so to write. 

So instead, I decided to write about daydreams. It sounds dumb, but it made sense to me then, and ironically it makes even more sense to me now. Basically, I wrote a stream-of-consciousness essay vindicating the act of daydreaming, which was and continues to be one of my favorite hobbies, if you can call it that. 

If nothing else, the essay was cute. It had flowery language, clever structure, allusions, metaphor, all in less than 250 words; an English teacher's wet dream, but wrapped up in a tidy little package. It was clean, it was creative, it was college application material. But it lacked conviction. 

I wrote it precisely __because__ it was clean and creative, not because I particularly believed in it. Daydreaming mattered to me, and I was kind of getting at the reasons in the essay, but I still suspected that something more standard and boring ("friendship", perhaps?) would matter __more__ if I had to compare them head-to-head. 

Now, I realize that I was right. 