= What Matters, Revisited

Approximately one and a half years ago, I was asked (via college application, no less) an interesting question. "What matters most to you, and why? (250 words)" 

Being the creative little shit that I was (and still am), I wrote a cute little essay about daydreaming. I wrote it because it made for an interesting essay, but little did I know how __right__ I was. At the time, I figured that my "real" answer to the question would be something along the lines of "friendship" or "happiness" or some other vague, wishy-washy buzzword. Now I realize that I was on to something in that essay. Daydreams __are__ fucking important. 

As backwards as it may sound, I'm only lucid when I'm daydreaming. 

Here I use daydreaming not in the falling-asleep-during-boring-lecture sense, or the fuck-that-girl-is-so-cute-I-wish-I-had-the-balls-to-ask-her-out sense. I think of daydreaming as more of a method of thought, or a state of mind. Kind of like an undirected form of introspection. 