= Define Extrapolate

Extrapolate is a blog.

Not a travel blog, or a food blog, or a book/movie review blog, though these are all things that I enjoy and will likely pop up in posts here and there. Extrapolate isn't a daily/weekly/{insert regular time interval}-ly journal blog either, though it might seem like it at times. 

Extrapolate is an ongoing record of the more interesting "ideas" that find their ways into my mind. I hesitate to use the word "ideas" here because (at least in my personal connotation-dictionary) __ideas__ are discrete, and useful in some compacity. The things I think about are hardly discrete and rarely useful, instead occupying the hazy intellectual territory at the intersection of personal experience and pattern recognition. 

That last bit probably makes zero sense to you, so let me try to explain. As I go about my exceptionally average life, I (like my 7+ billion fellow humans) inevitably accumulate a set of experiences, memories, ideas. __These__ are discrete; I can mentally point to a conversation I've had, or an article I've read, or a place I've been to. In isolation, these "points" are hardly worth thinking about, much less writing about. If I led a more interesting life, I could've made this blog a place to simply `Ctrl+C` `Ctrl+V` these experiences/ideas from my sensory receptors, with a dash of introspection. The analytical analog of an Instagram filter, basically.

But for better or worse, my life __is__ pretty mundane, so I spend a lot of my time daydreaming, iterating through all the possible interpretations of these ordinary experiences in their infinite permutations. I draw parallels between distinct points based on tenuous similarities, then substantiate them with further observation. I find/create metaphors and symbols in daily life where they previously didn't exist. I try to find a theory, a common thread, a line of best fit to interpolate and provide meaning to the points I've accumulated thus far. And as the name of the blog might suggest, I like to extend these narratives to areas that I am highly underqualified to talk about, including my own future. 

So take these posts with a grain of salt each. Each line of best fit has an R^2 value, and sometimes even I don't entirely subscribe to the ideas I come up with. I don't write these ideas down with the intention of convincing anyone. I write in the hopes that someone might identify with me; I write so that I don't forget; I write for the sake of writing. 

At this point, the use of all this first-person might have got you wondering, who am I? Well, I want to keep that more or less secret for now. I want to avoid judgment and commitment as much as possible. I want to keep this blog simple, unadulterated, and occasionally vulgar and/or controversial (this inaugural post is on the more tame/poetic side). I don't even know how long this thing is going to last, if I'm going to run out of motivation or ideas or time or whatever. You, reader, can help me out on this front by giving me things to write about http://ask.fm/xtrapolate[here]. 