= What Matters, Revisited

Approximately one and a half years ago, I was asked (via college application, no less) an interesting question. "What matters most to you, and why? (250 words)" 

Being the creative little shit that I was (and still am), I wrote a cute little essay about daydreaming. I wrote it because it made for an interesting essay, but little did I know how __right__ I was. At the time, I figured that my "real" answer to the question would be something along the lines of "friendship" or "happiness" or some other vague, wishy-washy buzzword. Now I realize that I was on to something in that essay. Daydreams __are__ fucking important. 

As backwards as it may sound, it's only when I'm daydreaming that I feel *lucid*. 

Here I use daydreaming not in the falling-asleep-during-boring-lecture sense, or the fuck-that-girl-is-so-cute-I-wish-I-had-the-balls-to-ask-her-out sense. I think of daydreaming as more of a method of thought, or a state of mind. Kind of like an undirected form of introspection. I think it might be easier to first explain what daydreaming __isn't__. 

By virtue of being a typical member of society, you're kind of guaranteed to have some sort of rhythm to your day/week/year/life. Whether it's a class schedule or a nine-to-five, there is a pattern, a sequence of motions you go through with some degree of regularity. After a few repetitions, it becomes muscle memory, autopilot. We're always so __busy__ that it becomes necessary for the sake of survival to sort of just sleepwalk through our days and weeks. It's efficient, it conserves energy. But it feels shitty. Not the blatant shittiness of stress or exhaustion, but a hollow shittiness. 

It's like being a sheep, being jostled and shuffled along by the fluffy, amorphous mass of your equally unconscious fellow sheep. You keep sleep/sheepwalking ever onwards because it's easy and you don't want to be left behind. Granted, it doesn't always look like this. I should clarify that this notion of consciousness has nothing to do with ambition or intelligence. You can be incredibly smart and driven and hard-working, but it doesn't matter if you just happen to be in a herd of particularly intelligent/fast/industrious sheep. You miss out on a whole lot by only looking forward.

I spend most of my waking hours in this semi-shitty, sheep-like state. I go through the motions. I apply my intellect outwardly, on whatever assignment or concept I find in front of me, but I don't __think__ about what I'm doing. I interact with friends and family, I laugh and I argue, but all of it feels involuntary. Knee-jerk. It's disturbingly easy to forget your own sentience and free will. 

In comparison to this state of non-REM, comatose, mental deadness, daydreaming feels refreshingly lucid. To continue the sheep analogy, daydreaming is like taking a moment to remind yourself where you are, where you're going. To figure out where you want to be, and where you want to be going. To ask the important questions: who/what is shepherding us in this general direction, and why? Or are we part of some organic, self-propagating system that shuffles ever-closer to cliff's edge by random chance and game theory? To daydream is to simulate the various "what if"s and "if only"s to see if we'd be better off heading down some other path. To daydream is to ask yourself what matters. 

And these questions __are__ important. After all, how are you going to find happiness if you don't know what it looks like? If you don't know what matters, nothing really matters. 

I hadn't really thought about it until now, but I started this blog in search of this type of lucidity. I like to write for the same reason that I like to travel and go on spontaneous late-night adventures: to interrupt whatever rhythm I've fallen into and temporarily reset my lucidity. So yes, daydreams matter. Stay lucid, friends. 
